name: auvnet_internship_assessment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
    
  # Firebase dependencies
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3

  # Freezed dependencies
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Auto Route
  auto_route: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generators
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/
