name: auvnet_internship_assessment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
    
  # Firebase dependencies
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3

  # Freezed dependencies
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Auto Route
  auto_route: ^10.0.1

  # Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Network
  dio: ^5.8.0+1
  http: ^1.4.0
  internet_connection_checker: ^3.0.1

  # UI
  flutter_svg: ^2.2.0
  flutter_native_splash: ^2.4.6
  vector_graphics: ^1.1.19
  formz: ^0.8.0
  animated_switcher_plus: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generators
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/logo.png
